title: "FIFA Svjetsko prvenstvo u Kataru 2022."
author: "Josip Došen"
description: "V. gimnazija"
permalink: /:title/
lang: "hr"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/stadioni.pdf", title: "Stadioni", icon: stadium}
  - {file: "README.md", title: "Utakmice", icon: ball}
  - {file: "/simboli.pdf", title: "Simboli", icon: smile}
  - {file: "/kontroverze.pdf", title: "Kontoverze", icon: search}
  - {url: "https://github.com/JosipDos", title: "Linkovi", icon: link}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:josip.dosen@skole.hr"}
  - {title: Github, icon: github, url: "https://github.com/JosipDos"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/dosen.josip/"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
